# Generated by Django 3.2.5 on 2021-07-13 13:35

from django.db import migrations, models
import starcatalogue.models


class Migration(migrations.Migration):

    dependencies = [
        ('starcatalogue', '0029_auto_20210518_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='star',
            name='json_celery_started',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='star',
            name='json_file',
            field=models.FileField(null=True, upload_to=starcatalogue.models.star_json_upload_to),
        ),
        migrations.AddField(
            model_name='star',
            name='json_files_celery_task_id',
            field=models.UUIDField(null=True),
        ),
        migrations.AddField(
            model_name='star',
            name='json_version',
            field=models.FloatField(null=True),
        ),
    ]
