# Generated by Django 3.2.7 on 2021-09-28 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starcatalogue', '0031_dataexport_in_data_archive'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataexport',
            name='doi',
            field=models.CharField(blank=True, max_length=22, null=True),
        ),
    ]
