# Generated by Django 3.2.8 on 2021-10-28 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starcatalogue', '0032_dataexport_doi'),
    ]

    operations = [
        migrations.AddField(
            model_name='zooniversesubject',
            name='metadata_version',
            field=models.FloatField(null=True),
        ),
    ]
