# Generated by Django 4.0.3 on 2022-03-09 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('starcatalogue', '0034_datarelease_aggregatedclassification'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataexport',
            name='data_release',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='starcatalogue.datarelease'),
        ),
    ]
