# Generated by Django 4.0.3 on 2022-03-19 16:34

from django.db import migrations, models
import starcatalogue.models


class Migration(migrations.Migration):

    dependencies = [
        ('starcatalogue', '0035_dataexport_data_release'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foldedlightcurve',
            name='classification',
        ),
        migrations.RemoveField(
            model_name='foldedlightcurve',
            name='classification_count',
        ),
        migrations.RemoveField(
            model_name='foldedlightcurve',
            name='period_uncertainty',
        ),
        migrations.AlterField(
            model_name='datarelease',
            name='version',
            field=models.FloatField(default=starcatalogue.models.get_next_data_release_version),
        ),
    ]
