# Generated by Django 4.0.3 on 2022-03-19 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starcatalogue', '0037_datarelease_aggregation_finished'),
    ]

    operations = [
        migrations.AddField(
            model_name='datarelease',
            name='active_at',
            field=models.DateTimeField(null=True),
        ),
    ]
