# Generated by Django 4.0.3 on 2022-03-19 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starcatalogue', '0038_datarelease_active_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datarelease',
            name='active_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
