# Generated by Django 4.0.3 on 2022-03-22 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starcatalogue', '0039_alter_datarelease_active_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='foldedlightcurve',
            name='updated_chi_squared',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='foldedlightcurve',
            name='updated_period_length',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='foldedlightcurve',
            name='updated_sigma',
            field=models.FloatField(null=True),
        ),
    ]
