# Generated by Django 4.0.3 on 2022-03-22 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starcatalogue', '0040_foldedlightcurve_updated_chi_squared_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aggregatedclassification',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='foldedlightcurve',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='star',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='zooniversesubject',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
