# Generated by Django 4.0.3 on 2022-04-06 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starcatalogue', '0042_datarelease_generate_export'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataexport',
            name='half_period',
            field=models.BooleanField(choices=[(True, 'on'), (False, 'off')], default=True),
        ),
        migrations.AlterField(
            model_name='aggregatedclassification',
            name='period_uncertainty',
            field=models.IntegerField(choices=[(0, 'Certain'), (1, 'Uncertain'), (2, 'Half')]),
        ),
    ]
