# Generated by Django 4.2.11 on 2024-04-03 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starcatalogue', '0043_dataexport_half_period_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataexport',
            name='doi',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
